before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y fonts-dejavu-core
addons:
  apt:
    packages:
      - latex-beamer
      - texlive-xetex
      - texlive-latex-recommended
      - texlive-latex-extra 
      - texlive-fonts-recommended
      - lmodern
script:
    - make -C epam/LinuxEssBash/ 01-intro.pdf
