addons:
  apt:
    packages:
      - latex-beamer
      - texlive-latex-recommended
      - texlive-latex-extra 
      - texlive-fonts-recommended
script:
    - make -C epam/LinuxEssBash/ 01-intro.pdf
