addons:
  apt:
    packages:
      - latex-beamer
      - texlive-xetex
      - texlive-latex-recommended
      - texlive-latex-extra 
      - texlive-fonts-recommended
      - lmodern
script:
    - fc-list :lang=ru
    - make -C epam/LinuxEssBash/ 01-intro.pdf
