Vagrant.configure("2") do |config|
  config.vm.box = "centos/8_1"
  config.vm.define "wsgi" do |server|
    server.vm.host_name = 'pyapp'
    server.vm.network :private_network, ip: "10.0.0.10"
    server.vm.network "forwarded_port", guest: 80, host: 8081
    server.vm.provision "shell", path: "deploy.sh"
  end
end


