Vagrant.configure("2") do |config|
  config.vm.box = "centos/8_1"
  config.vm.define "server" do |server|
    server.vm.host_name = 'server'
    server.vm.network :private_network, ip: "10.0.0.10"
    server.vm.provision "shell", path: "deploy.sh"
  end

  config.vm.define "client" do |client|
    client.vm.host_name = 'client'
    client.vm.network :private_network, ip: "10.0.0.11"
    client.vm.provision "shell", path: "deploycli.sh"
  end
end

