FROM ubuntu:latest

RUN apt-get update && \
    apt-get -y install latex-beamer texlive-xetex texlive-latex-recommended \
    texlive-generic-recommended texlive-latex-extra texlive-fonts-recommended \
    lmodern && \
    apt-get clean 
 

