FROM finalduty/archlinux:weekly

RUN pacman -Syu --noconfirm  texlive-bin \
        texlive-core \
        texlive-langcyrillic \
        texlive-latexextra \
        texlive-pictures ;\
    pacman -Scc --noconfirm
