pipeline
{
    agent
    {
        dockerfile
        {
            dir 'itacademy/LinuxEssBash/buildenv'
        }
    }
    stages
    {
        stage("Build")
        {
            steps 
            {
                sh "make --directory=itacademy/LinuxEssBash/"
            }
        }
        stage("Test")
        {
            steps 
            {
                echo "Test containers"
            }
        }
        stage("Deploy")
        {
            steps
            {
                echo "Copy artifacts"
            }
        }
    }
}
