pipeline
{
    agent
    {
        dockerfile
        {
            dir 'itacademy/LinuxEssBash/buildenv'
        }
    }
    stages
    {
        stage("Build")
        {
            steps 
            {
                sh "make --directory=itacademy/LinuxEssBash/"
                sh "cd itacademy/LinuxEssBash/; latexmk -pdfxe ; cd -"
            }
        }
        stage("Test")
        {
            steps 
            {
                sh "ls itacademy/LinuxEssBash/"
            }
        }
        stage("Deploy")
        {
            steps
            {
                echo "Copy artifacts to workspace"
                // Archive the build output artifacts.
                archiveArtifacts artifacts: 'itacademy/LinuxEssBash/*.pdf'
            }
        }
    }
}
