pipeline
{
    agent
    {
        dockerfile
        {
            dir itacademy/LinuxEssBash/buildenv
        }
    }
    stages
    {
        stage("Build")
        {
            steps 
            {
                echo "Build files"
                sh "ls -R"
            }
        }
        stage("Test")
        {
            steps 
            {
                echo "Test containers"
            }
        }
        stage("Deploy")
        {
            steps
            {
                echo "Copy artifacts"
            }
        }
    }
}
